Miner updates: Updated OpenCL version, enabled CUDA building, improved SIGSEGV failure rates
dominant-strategies/quai-gpu-miner-archive pull request #12
Opened 2023-11-06 17:05 UTC by jdowning100

2023-11-06 17:44 UTC, Djadih requested changes
Really excited about the hashrate increases for later AMD cards, thank you for bringing this in. Change requests are with regard to the second commit.

2023-11-06 17:44 UTC, Djadih commented on libpoolprotocols/PoolManager.h
> +    unsigned connectionMaxRetries = 30;  // Max number of connection retries
Can we make these changes a separate commit.

2023-11-06 17:44 UTC, Djadih commented on CMakeLists.txt
> -option(ETHASHCUDA "Build with CUDA mining" OFF)
This can't be made default because it will fail for people running on AMD. But we are adding a command parameter to the docs.

2023-11-06 17:44 UTC, Djadih commented on ethcoreminer/main.cpp
> +            break;
I would say we should leave this out or, add it to the end of the code so that other cleanup can happen first.

2023-11-06 17:44 UTC, Djadih commented on libethash-cuda/CMakeLists.txt
> +	list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_86,code=sm_86")
We should move this to line 39 because it will crash if the cuda version doesn't include support for 86. For example I believe Hive's by default ships a cuda version that doesn't have 86.

2023-11-06 18:35 UTC, jdowning100 commented on libethash-cuda/CMakeLists.txt
> +	list(APPEND CUDA_NVCC_FLAGS "-gencode arch=compute_86,code=sm_86")
Hive OS (any OS, in fact) won't be able to build this without the CUDA toolkit. But you're right, we should check if CUDA 12 is installed before building for 8.6

2023-11-06 21:14 UTC, jdowning100 commented on CMakeLists.txt
> -option(ETHASHCUDA "Build with CUDA mining" OFF)
Fixed

2023-11-09 18:28 UTC, Djadih approved these changes

2023-11-09 18:32 UTC, merged